Vagrant.configure("2") do |config|

    config.vm.boot_timeout = 900

    config.vm.define "winser2019" do |winser2019|
      winser2019.vm.box = "jborean93/WindowsServer2019"
      winser2019.vm.communicator = :winssh
      winser2019.winssh.shell = :powershell

      winser2019.vm.provider :libvirt do |domain|
        domain.cpus = 1
        domain.memory = 4096
        domain.storage :file, :size => '20G'
        domain.forward_ssh_port = true
      end
    end
  end
