Vagrant.configure("2") do |config|

    config.vm.boot_timeout = 900

    config.vm.define "win10" do |win10|
        win10.vm.box = "peru/windows-10-enterprise-x64-eval"
        win10.vm.box_version = "20221202.01"
        win10.vm.communicator = :winssh
        win10.winssh.shell = :powershell

        win10.vm.provider :libvirt do |domain|
          domain.cpus = 1
          domain.memory = 4096
          domain.storage :file, :size => '20G'
      end
    end
  end
