Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      # https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html
      vbox.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    config.vm.network "public_network"

    # Ubuntu 20.04 (Focal) guest VM
    config.vm.define "kvmiv_ubuntu2004" do |kvmiv|
      kvmiv.vm.box = "generic/ubuntu2004"
  
      kvmiv.vm.synced_folder ".", "/vagrant"
      kvmiv.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../playbooks/kvm-introvirt.yml"
        ansible.verbose = "vvv"
      end
    end
  end
