Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      # https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html
      vbox.customize ["modifyvm", :id, "--nested-hw-virt", "on"]

      vbox.memory = 8192
      vbox.cpus = 3
    end

    config.vm.network "public_network"

    # Ubuntu 20.04 (Focal) guest VM
    config.vm.define "ivhost_ubuntu2004" do |ivhost|
      ivhost.vm.box = "LethalServant/ivkvmhost"
      ivhost.vm.box_version = "0.1.0"

      ivhost.vm.synced_folder ".", "/vagrant"
      ivhost.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../playbooks/ivhost.yml"
        ansible.verbose = "vvv"
      end
      #config.vm.provision "shell", inline: <<-SHELL
      #  pwd
      #  wget https://github.com/chp-io/efi-shell/releases/download/edk2-stable202202/Shell.efi
      #  mkdir -p storage/EFI/BOOT
      #  echo "echo Hello world!" > storage/startup.nsh
      #  echo "reset -s" >> storage/startup.nsh
      #  mv Shell.efi storage/EFI/BOOT/BOOTX64.EFI
      #  qemu-system-x86_64 -enable-kvm -machine q35 -cpu host -m 8G -bios /usr/share/OVMF/OVMF_CODE.fd -name guest=ivguest -nographic -drive format=raw,file=fat:rw:storage
      #SHELL
    end
  end
