Vagrant.configure("2") do |config|

    config.vm.provider "virtualbox" do |vbox|
      vbox.gui = false
      # https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html
      vbox.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
    end

    config.vm.network "public_network"

    # Ubuntu 20.04 (Focal) guest VM
    config.vm.define "ivhost_ubuntu2004" do |ivhost|
      ivhost.vm.box = "LethalServant/ivkvmhost"
      ivhost.vm.box_version = "0.1.0"
  
      ivhost.vm.synced_folder ".", "/vagrant"
      ivhost.vm.provision "ansible" do |ansible|
        ansible.playbook = "../../playbooks/ivhost.yml"
        ansible.verbose = "vvv"
      end
    end
  end