Vagrant.configure("2") do |config|

    # Ubuntu 20.04 (Focal) guest VM
    config.vm.define "ubuntu2004" do |test|
      test.vm.box = "generic/ubuntu2004"
      
      test.vm.provider :libvirt do |domain|
        domain.cpus = 1
        domain.memory = 2096
      end
    end
  end
