name: macos test

on:
  push:
    paths-ignore: ['**.md']
  pull_request:
    branches: [ main ]

jobs:
  # build_kvm_introvirt:
  #   runs-on: macos-12
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v3
  #     - name: Install Ansible via python
  #       run: python3 -m pip install ansible
  #     - name: Run MacOS System Checks
  #       run: ./macos-system-checks.sh
  #     - name: Build kvm-introvirt for specific kernel
  #       run: ./build-vbox-ivkvm-builder.sh
  #     - name: Archive kvm introvirt deb packages
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: kvm-introvirt
  #         path: vagrant/kvm_introvirt_builder/kvm-introvirt*.deb
  test_iv:
    runs-on: macos-12
    # needs: build_kvm_introvirt
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Ansible via python
        run: python3 -m pip install ansible
      - name: Run MacOS System Checks
        run: ./macos-system-checks.sh
      - name: Build ivhost to test introvirt
        run: ./build-vbox-ivhost.sh
